# .github/workflows/app.yaml
name: My Python Project
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install pipenv
        working-directory: ./data_processing
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        working-directory: ./data_processing
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Run test suite
        working-directory: ./data_processing
        run: |
          pipenv run test -svvv

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn

      - name: Run the tests
        working-directory: ./frontend
        run: yarn test

      # doesn't quite work because of priv aws config
      # - name: Build
      #   working-directory: ./frontend
      #   run: yarn build